In [1]:
!pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Collecting mlxtend
  Downloading mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: scipy>=1.16.3 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from mlxtend) (1.17.1)
Requirement already satisfied: numpy>=2.3.5 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from mlxtend) (2.4.4)
Requirement already satisfied: pandas>=2.3.3 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from mlxtend) (3.0.2)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from mlxtend) (1.9.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from mlxtend) (3.10.9)
Requirement already satisfied: joblib>=1.5.2 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from matplotlib>=3.10.8->mlxtend) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from matplotlib>=3.10.8->mlxtend) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from matplotlib>=3.10.8->mlxtend) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from pandas>=2.3.3->mlxtend) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.20.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\royal wala\appdata\roaming\python\python314\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Downloading mlxtend-0.25.0-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.4 MB 1.2 MB/s eta 0:00:01
   ------------------------------ --------- 1.0/1.4 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 1.9 MB/s  0:00:03
Installing collected packages: mlxtend
Successfully installed mlxtend-0.25.0

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [23]:

transactions = [
    ['Milk','Bread','Butter'],
    ['Bread','Butter'],
    ['Milk','Bread'],
    ['Milk','Butter'],
    ['Bread','Butter'],
    ['Milk','Bread','Butter']
]

In [24]:
# Convert transactions into one hot encoded format
# milk Bread Butter
# 1     1    1
# 0     1    1
# 1     1    0
# etc

In [25]:
te = TransactionEncoder()

In [26]:
te_array = te.fit(transactions).transform(transactions)

In [27]:
te_array

array([[ True,  True,  True],
       [ True,  True, False],
       [ True, False,  True],
       [False,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [28]:
df = pd.DataFrame(te_array, columns =te.columns_)

In [29]:
df

   Bread  Butter   Milk
0   True    True   True
1   True    True  False
2   True   False   True
3  False    True   True
4   True    True  False
5   True    True   True

In [30]:
frequent_itemsets = apriori(df, min_support = 0.5, use_colnames = True)

In [31]:
frequent_itemsets

    support                    itemsets
0  0.833333          frozenset({Bread})
1  0.833333         frozenset({Butter})
2  0.666667           frozenset({Milk})
3  0.666667  frozenset({Butter, Bread})
4  0.500000    frozenset({Bread, Milk})
5  0.500000   frozenset({Butter, Milk})

In [32]:
# Generate Association Rules
rules = association_rules( frequent_itemsets, metric= 'confidence', min_threshold=0.7)

In [33]:
rules

           antecedents          consequents  antecedent support  consequent support  ...  zhangs_metric   jaccard  certainty  kulczynski
0  frozenset({Butter})   frozenset({Bread})            0.833333            0.833333  ...          -0.20  0.666667       -0.2       0.800
1   frozenset({Bread})  frozenset({Butter})            0.833333            0.833333  ...          -0.20  0.666667       -0.2       0.800
2    frozenset({Milk})   frozenset({Bread})            0.666667            0.833333  ...          -0.25  0.500000       -0.5       0.675
3    frozenset({Milk})  frozenset({Butter})            0.666667            0.833333  ...          -0.25  0.500000       -0.5       0.675

[4 rows x 14 columns]

In [34]:
 
transactions = [
    ['Bread','Butter','Milk'],
    ['Bread','Butter'],
    ['Bread','Butter','Eggs'],
    ['Bread','Butter','Milk'],
    ['Bread','Butter'],
    ['Bread','Butter','Milk'],
    ['Milk','Eggs'],
    ['Bread','Butter','Milk'],
    ['Bread']
]

In [35]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori , association_rules

In [37]:
te = TransactionEncoder()

In [38]:
te_array = te.fit(transactions).transform(transactions)

In [39]:
te_array

array([[ True,  True, False,  True],
       [ True,  True, False, False],
       [ True,  True,  True, False],
       [ True,  True, False,  True],
       [ True,  True, False, False],
       [ True,  True, False,  True],
       [False, False,  True,  True],
       [ True,  True, False,  True],
       [ True, False, False, False]])

In [40]:
df = pd.DataFrame(te_array, columns = te.columns_)

In [41]:
df

   Bread  Butter   Eggs   Milk
0   True    True  False   True
1   True    True  False  False
2   True    True   True  False
3   True    True  False   True
4   True    True  False  False
5   True    True  False   True
6  False   False   True   True
7   True    True  False   True
8   True   False  False  False

In [42]:
frequent_itemsets = apriori(df, min_support =0.3, use_colnames =True )

In [43]:
frequent_itemsets

    support                          itemsets
0  0.888889                frozenset({Bread})
1  0.777778               frozenset({Butter})
2  0.555556                 frozenset({Milk})
3  0.777778        frozenset({Butter, Bread})
4  0.444444          frozenset({Bread, Milk})
5  0.444444         frozenset({Butter, Milk})
6  0.444444  frozenset({Butter, Bread, Milk})

In [44]:
rules = association_rules(frequent_itemsets,metric= 'confidence', min_threshold= 0.80)

In [45]:
rules

                 antecedents          consequents  antecedent support  ...   jaccard  certainty  kulczynski
0        frozenset({Butter})   frozenset({Bread})            0.777778  ...  0.875000     1.0000    0.937500
1         frozenset({Bread})  frozenset({Butter})            0.888889  ...  0.875000     0.4375    0.937500
2  frozenset({Butter, Milk})   frozenset({Bread})            0.444444  ...  0.500000     1.0000    0.750000
3   frozenset({Bread, Milk})  frozenset({Butter})            0.444444  ...  0.571429     1.0000    0.785714

[4 rows x 14 columns]

In [47]:
rules[['antecedents','consequents','support','confidence','lift']]

                 antecedents          consequents   support  confidence      lift
0        frozenset({Butter})   frozenset({Bread})  0.777778       1.000  1.125000
1         frozenset({Bread})  frozenset({Butter})  0.777778       0.875  1.125000
2  frozenset({Butter, Milk})   frozenset({Bread})  0.444444       1.000  1.125000
3   frozenset({Bread, Milk})  frozenset({Butter})  0.444444       1.000  1.285714