In [88]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [89]:
df = pd.read_csv(r"F:\Machine Learning\Machine_Learning\DataModel\market.csv", sep=';')

In [90]:
df.shape

(464, 22)

In [91]:
df.shape

(464, 22)

In [92]:
df.head()

,Bread,Honey,Bacon,Toothpaste,Banana,Apple,Hazelnut,Cheese,Meat,Carrot,...,Milk,Butter,ShavingFoam,Salt,Flour,HeavyCream,Egg,Olive,Shampoo,Sugar
0,1,0,1,0,1,1,1,0,0,1,...,0,0,0,0,0,1,1,0,0,1
1,1,1,1,0,1,1,1,0,0,0,...,1,1,0,0,1,0,0,1,1,0
2,0,1,1,1,1,1,1,1,1,0,...,1,0,1,1,1,1,1,0,0,1
3,1,1,0,1,0,1,0,0,0,0,...,1,0,0,0,1,0,1,1,1,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [93]:
df.isnull().sum()

Bread          0
Honey          0
Bacon          0
Toothpaste     0
Banana         0
Apple          0
Hazelnut       0
Cheese         0
Meat           0
Carrot         0
Cucumber       0
Onion          0
Milk           0
Butter         0
ShavingFoam    0
Salt           0
Flour          0
HeavyCream     0
Egg            0
Olive          0
Shampoo        0
Sugar          0
dtype: int64

In [94]:
df.duplicated().sum()

np.int64(7)

In [95]:
for col in df.columns:
    vals = set(df[col].dropna().unique())
    if not vals.issubset({0,1}):
        print(col,vals)

In [99]:
df.to_csv(r'DataModel\market_clean.csv',index =False)

In [100]:
df = df.drop_duplicates()

In [101]:
df

,Bread,Honey,Bacon,Toothpaste,Banana,Apple,Hazelnut,Cheese,Meat,Carrot,...,Milk,Butter,ShavingFoam,Salt,Flour,HeavyCream,Egg,Olive,Shampoo,Sugar
0,1,0,1,0,1,1,1,0,0,1,...,0,0,0,0,0,1,1,0,0,1
1,1,1,1,0,1,1,1,0,0,0,...,1,1,0,0,1,0,0,1,1,0
2,0,1,1,1,1,1,1,1,1,0,...,1,0,1,1,1,1,1,0,0,1
3,1,1,0,1,0,1,0,0,0,0,...,1,0,0,0,1,0,1,1,1,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,0,1,1,0,0,1,1,1,1,1,...,1,1,0,0,1,1,1,1,1,0
460,0,0,1,0,0,0,1,0,1,0,...,0,0,1,0,0,0,1,0,0,1
461,0,0,0,0,0,1,0,1,1,0,...,1,0,0,0,0,0,1,0,0,0
462,1,0,0,1,1,0,1,1,0,1,...,1,0,0,0,1,0,1,1,0,1
463,1,0,1,0,0,0,1,0,0,1,...,1,0,1,0,1,1,1,0,0,1

In [102]:
#mar = TransactionEncoder()

In [103]:
#mar_array = mar.fit(df).transform(df)

In [104]:
#mar_array

In [105]:
df = df.astype(bool)

In [106]:
# df is already binary — feed directly into apriori
frequent_itemsets = apriori(df, min_support = 0.05, use_colnames =True)

In [107]:
frequent_itemsets

       support                                           itemsets
0     0.413567                                 frozenset({Bread})
1     0.420131                                 frozenset({Honey})
2     0.433260                                 frozenset({Bacon})
3     0.389497                            frozenset({Toothpaste})
4     0.452954                                frozenset({Banana})
...        ...                                                ...
4153  0.050328  frozenset({Onion, ShavingFoam, Butter, Hazelnu...
4154  0.050328    frozenset({Onion, Meat, Butter, Cheese, Bacon})
4155  0.054705  frozenset({Meat, ShavingFoam, Butter, Cheese, ...
4156  0.054705  frozenset({Onion, ShavingFoam, Butter, Cheese,...
4157  0.050328  frozenset({Meat, ShavingFoam, Butter, Cheese, ...

[4158 rows x 2 columns]

In [108]:
# Generate Association Rules
rules = association_rules(frequent_itemsets, metric = 'confidence', min_threshold=0.3)

In [109]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Bread}),frozenset({Honey}),0.413567,0.420131,0.203501,0.492063,1.171214,1.0,0.029749,1.141617,0.249278,0.322917,0.124049,0.488219
1,frozenset({Honey}),frozenset({Bread}),0.420131,0.413567,0.203501,0.484375,1.171214,1.0,0.029749,1.137325,0.252100,0.322917,0.120744,0.488219
2,frozenset({Bacon}),frozenset({Bread}),0.433260,0.413567,0.205689,0.474747,1.147934,1.0,0.026507,1.116479,0.227388,0.320819,0.104327,0.486051
3,frozenset({Bread}),frozenset({Bacon}),0.413567,0.433260,0.205689,0.497354,1.147934,1.0,0.026507,1.127514,0.219752,0.320819,0.113093,0.486051
4,frozenset({Toothpaste}),frozenset({Bread}),0.389497,0.413567,0.177243,0.455056,1.100321,1.0,0.016160,1.076135,0.149343,0.283217,0.070749,0.441814
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20302,"frozenset({Hazelnut, Cheese, ShavingFoam})","frozenset({Meat, Butter})",0.113786,0.166302,0.050328,0.442308,2.659666,1.0,0.031405,1.494907,0.704133,0.219048,0.331062,0.372470
20303,"frozenset({Butter, Cheese, ShavingFoam})","frozenset({Meat, Hazelnut})",0.122538,0.194748,0.050328,0.410714,2.108949,1.0,0.026464,1.366488,0.599263,0.188525,0.268197,0.334571
20304,"frozenset({Butter, Hazelnut, ShavingFoam})","frozenset({Meat, Cheese})",0.109409,0.207877,0.050328,0.460000,2.212842,1.0,0.027585,1.466894,0.615426,0.188525,0.318287,0.351053
20305,"frozenset({Butter, Cheese, Hazelnut})","frozenset({Meat, ShavingFoam})",0.124726,0.185996,0.050328,0.403509,2.169453,1.0,0.027130,1.364654,0.615870,0.193277,0.267214,0.337049
20306,"frozenset({Meat, Butter})","frozenset({Hazelnut, Cheese, ShavingFoam})",0.166302,0.113786,0.050328,0.302632,2.659666,1.0,0.031405,1.270798,0.748488,0.219048,0.213093,0.372470

In [110]:
rules[['antecedents','consequents','support','confidence','lift']]

,antecedents,consequents,support,confidence,lift
0,frozenset({Bread}),frozenset({Honey}),0.203501,0.492063,1.171214
1,frozenset({Honey}),frozenset({Bread}),0.203501,0.484375,1.171214
2,frozenset({Bacon}),frozenset({Bread}),0.205689,0.474747,1.147934
3,frozenset({Bread}),frozenset({Bacon}),0.205689,0.497354,1.147934
4,frozenset({Toothpaste}),frozenset({Bread}),0.177243,0.455056,1.100321
...,...,...,...,...,...
20302,"frozenset({Hazelnut, Cheese, ShavingFoam})","frozenset({Meat, Butter})",0.050328,0.442308,2.659666
20303,"frozenset({Butter, Cheese, ShavingFoam})","frozenset({Meat, Hazelnut})",0.050328,0.410714,2.108949
20304,"frozenset({Butter, Hazelnut, ShavingFoam})","frozenset({Meat, Cheese})",0.050328,0.460000,2.212842
20305,"frozenset({Butter, Cheese, Hazelnut})","frozenset({Meat, ShavingFoam})",0.050328,0.403509,2.169453
20306,"frozenset({Meat, Butter})","frozenset({Hazelnut, Cheese, ShavingFoam})",0.050328,0.302632,2.659666