In [5]:
%pip install yfinance

Collecting yfinance
  Using cached yfinance-1.5.1-py2.py3-none-any.whl.metadata (6.2 kB)
Collecting pandas>=1.3.0 (from yfinance)
  Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.16.5 (from yfinance)
  Using cached numpy-2.5.1-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Collecting requests>=2.31 (from yfinance)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting multitasking>=0.0.7 (from yfinance)
  Using cached multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\royal wala\appdata\roaming\python\python312\site-packages (from yfinance) (4.10.0)
Collecting pytz>=2022.5 (from yfinance)
  Using cached pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Using cached peewee-4.1.1-py3-none-any.whl.metadata (10 kB)
Collecting beautifulsoup4>=4.11.1 (from yfinance)
  Using cached beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting curl_cffi>=0.15 (from yfinance)
  Using cached curl_cffi-0.15.0-cp310-abi3-win_amd64.whl.metadata (18 kB)
Collecting protobuf>=3.19.0 (from yfinance)
  Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting websockets>=13.0 (from yfinance)
  Using cached websockets-16.0-cp312-cp312-win_amd64.whl.metadata (7.0 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4>=4.11.1->yfinance)
  Using cached soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\royal wala\appdata\roaming\python\python312\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Collecting cffi>=2.0.0 (from curl_cffi>=0.15->yfinance)
  Using cached cffi-2.0.0-cp312-cp312-win_amd64.whl.metadata (2.6 kB)
Collecting certifi>=2024.2.2 (from curl_cffi>=0.15->yfinance)
  Using cached certifi-2026.6.17-py3-none-any.whl.metadata (2.5 kB)
Collecting rich (from curl_cffi>=0.15->yfinance)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\royal wala\appdata\roaming\python\python312\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Collecting tzdata (from pandas>=1.3.0->yfinance)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.31->yfinance)
  Downloading charset_normalizer-3.4.8-cp312-cp312-win_amd64.whl.metadata (42 kB)
Collecting idna<4,>=2.5 (from requests>=2.31->yfinance)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.31->yfinance)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pycparser (from cffi>=2.0.0->curl_cffi>=0.15->yfinance)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: six>=1.5 in c:\users\royal wala\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Collecting markdown-it-py>=2.2.0 (from rich->curl_cffi>=0.15->yfinance)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\royal wala\appdata\roaming\python\python312\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached yfinance-1.5.1-py2.py3-none-any.whl (144 kB)
Using cached beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Using cached curl_cffi-0.15.0-cp310-abi3-win_amd64.whl (1.7 MB)
Using cached multitasking-0.0.13-py3-none-any.whl (16 kB)
Using cached numpy-2.5.1-cp312-cp312-win_amd64.whl (12.4 MB)
Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
Using cached peewee-4.1.1-py3-none-any.whl (170 kB)
Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Using cached pytz-2026.2-py2.py3-none-any.whl (510 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached websockets-16.0-cp312-cp312-win_amd64.whl (178 kB)
Using cached certifi-2026.6.17-py3-none-any.whl (133 kB)
Using cached cffi-2.0.0-cp312-cp312-win_amd64.whl (183 kB)
Downloading charset_normalizer-3.4.8-cp312-cp312-win_amd64.whl (162 kB)
Using cached idna-3.18-py3-none-any.whl (65 kB)
Using cached soupsieve-2.8.4-py3-none-any.whl (37 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pytz, peewee, multitasking, websockets, urllib3, tzdata, soupsieve, pycparser, protobuf, numpy, mdurl, idna, charset_normalizer, certifi, requests, pandas, markdown-it-py, cffi, beautifulsoup4, rich, curl_cffi, yfinance
Successfully installed beautifulsoup4-4.15.0 certifi-2026.6.17 cffi-2.0.0 charset_normalizer-3.4.8 curl_cffi-0.15.0 idna-3.18 markdown-it-py-4.2.0 mdurl-0.1.2 multitasking-0.0.13 numpy-2.5.1 pandas-3.0.3 peewee-4.1.1 protobuf-7.35.1 pycparser-3.0 pytz-2026.2 requests-2.34.2 rich-15.0.0 soupsieve-2.8.4 tzdata-2026.2 urllib3-2.7.0 websockets-16.0 yfinance-1.5.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import yfinance as yf
from utils.data_loader import download_stock_data

In [7]:
from datetime import date

In [8]:
df = download_stock_data('AAPL',date(2018,1,1),date.today())

[*********************100%***********************]  1 of 1 completed

In [10]:
df = df.reset_index()

In [14]:
df.head(2)

Price  index       Date      Close       High        Low       Open     Volume
0          0 2018-01-02  40.267082  40.276435  39.565809  39.776193  102223600
1          1 2018-01-03  40.260059  40.802379  40.196947  40.330187  118071600

In [12]:
df.columns =df.columns.get_level_values(0)

In [13]:
df.head(2)

Price  index       Date      Close       High        Low       Open     Volume
0          0 2018-01-02  40.267082  40.276435  39.565809  39.776193  102223600
1          1 2018-01-03  40.260059  40.802379  40.196947  40.330187  118071600